# Generated by Django 4.2.5 on 2023-09-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myntra_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
