# Generated by Django 4.2.5 on 2023-09-23 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myntra_app', '0004_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_subcategory',
        ),
        migrations.CreateModel(
            name='ProductsList',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image_path', models.CharField(max_length=225)),
                ('Product_subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myntra_app.product_subcategory')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='products_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myntra_app.productslist'),
        ),
    ]
